apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: skillfybank
type: Opaque
data:
  # echo -n 'skillfybank-user' | base64
  db-username: c2tpbGxmeWJhbmstdXNlcg==
  # echo -n 'SkillfyBank2024!' | base64  
  db-password: U2tpbGxmeUJhbmsyMDI0IQ==
  # echo -n 'skillfybank-db' | base64
  db-name: c2tpbGxmeWJhbmstZGI=
